### ISSUE TITLE
rdmseed.m update

### ISSUE THREAD

**Issue by beaudu** [asl-usgs/seistestmlab#3]
Hi,
You should upgrade the rdmseed.m version using the last release available here:
   http://www.mathworks.com/matlabcentral/fileexchange/28803
There is A LOT of improvements (since 2010 !), including the bitcmp problem, appeared and quickly fixed in 2013.
Thanks,
F. Beauducel (author of rdmseed.m)

**Comment by aringler-usgs** [comment]
Thanks for sending me this link.  We appreciate the work you did into writing that code.  I have updated to your newest version.

Best,
Adam
